<!doctype html><html lang="zh-tw">
<head>
    <meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="程式難免會發生錯誤，在先前的幾堂課中進行的練習雖然簡單，然而你一定也遇上了一些錯誤，你會怎麼處理這些錯誤呢？提供更清楚的錯誤訊息？事先檢查運行條件以避免錯誤？或者是在錯誤發生後，趕緊收拾善後，避免浪費...">

<meta property="og:locale" content="zh_TW">
<meta property="og:title" content="Python 3 Tutorial 第五堂（1）Shit happens!">
<meta property="og:type" content="article">
<meta property="og:url" content="https://openhome.cc/Gossip/CodeData/PythonTutorial/ShitHappensPy.html">
<meta property="og:image" content="https://openhome.cc/Gossip/images/caterpillar_small.jpg">
<meta property="og:site_name" content="OPENHOME.CC">
<meta property="og:description" content="程式難免會發生錯誤，在先前的幾堂課中進行的練習雖然簡單，然而你一定也遇上了一些錯誤，你會怎麼處理這些錯誤呢？提供更清楚的錯誤訊息？事先檢查運行條件以避免錯誤？或者是在錯誤發生後，趕緊收拾善後，避免浪費...">

    <title>Python 3 Tutorial 第五堂（1）Shit happens!</title>

<link rel="stylesheet" href="../../css/pure-0.6.0/pure-min.css">

    <!--[if lte IE 8]>
        <link rel="stylesheet" href="../../css/layouts/side-menu-old-ie.css">
    <![endif]-->
    <!--[if gt IE 8]><!-->
        <link rel="stylesheet" href="../../css/layouts/side-menu.css">
    <!--<![endif]-->
  

     <link rel="stylesheet" href="../../css/caterpillar.css">
     <script async src="../../google-code-prettify/run_prettify.js"></script>
<!-- 網頁層級廣告 --><script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script><script>(adsbygoogle =window.adsbygoogle || []).push({google_ad_client: "ca-pub-9750319131714390",enable_page_level_ads: true });</script></head>
<body>

<div id="layout">
    <!-- Menu toggle -->
    <a href="ShitHappensPy.html#menu" id="menuLink" class="menu-link">
        <!-- Hamburger icon -->
        <span></span>
    </a>
    <div id="menu">
        <div class="pure-menu">
            <a class="pure-menu-heading" href="index.html">回 Python Tutorial</a>
            <ul class="pure-menu-list">
                <li class="pure-menu-item"><br><div class="social" style="text-align: center;"><a href="http://twitter.com/caterpillar"><img title="Twitter" alt="Twitter" src="../../images/twitter.png"></a> <a href="http://www.facebook.com/openhome.cc"><img title="Facebook" alt="Facebook" src="../../images/facebook.png"></a> </div><br> <div id="search box"><script>(function() {var cx = 'partner-pub-9750319131714390:3926766884';var gcse = document.createElement('script');gcse.type = 'text/javascript';gcse.async = true;gcse.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') + '//www.google.com/cse/cse.js?cx=' + cx;var s = document.getElementsByTagName('script')[0];s.parentNode.insertBefore(gcse, s);})();</script><gcse:searchbox-only></gcse:searchbox-only></div><br><div class="ad" style="text-align: center;"><script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- 2015 新版型 160 x 600 廣告 -->
<ins class="adsbygoogle"
     style="display:inline-block;width:160px;height:600px"
     data-ad-client="ca-pub-9750319131714390"
     data-ad-slot="3747048883"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script></div></li>
            </ul>
        </div>
    </div>

    <main id="main">
        <header class="header">
            <h1>Python 3 Tutorial 第五堂（1）Shit happens!</h1>
        </header>

        <article class="content">
            <br><div class="ad-3" style="text-align: center;"><script async="" src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script><!-- 2015 新版型回應式廣告 --><ins class="adsbygoogle" style="display:block" data-ad-client="ca-pub-9750319131714390" data-ad-slot="7104125683" data-ad-format="auto"></ins><script>(adsbygoogle = window.adsbygoogle || []).push({});</script></div> 
            
            <p>程式難免會發生錯誤，在先前的幾堂課中進行的練習雖然簡單，然而你一定也遇上了一些錯誤，你會怎麼處理這些錯誤呢？提供更清楚的錯誤訊息？事先檢查運行條件以避免錯誤？或者是在錯誤發生後，趕緊收拾善後，避免浪費系統資源？</p>
<p>「怎麼處理錯誤」是很值得也必須思考的課題，如果你從未在這方面認真過，建議日後若有時間，可以參考一下以下幾篇文章：</p>
<ul>
<li>〈<a href="../../Programmer/Exception.html">Shit Happens！該抓還是該丟？</a>〉</li>
<li>〈<a href="../../Programmer/DefensiveProgramming.html">避免隱藏錯誤的防禦性設計</a>〉</li>
<li>〈<a href="../../Programmer/FunctionalErrorHandling.html">函數式風格錯誤處理</a>〉</li>
<li>〈<a href="../../Programmer/RefactorErrorHandling.html">重構錯誤處理程式</a>〉</li>
<li>〈<a href="../../Programmer/GoErrorPanic.html">Go的error與panic</a>〉</li>
</ul>
<h1><code>try</code>、<code>except</code></h1>
<p>來個實際的例子吧！在〈<a href="UnicodeBasicIOPy3.html">Python 3 Tutorial 第二堂（1）Unicode 支援、基本 I/O</a>〉中，我們看過讀取檔案的一個範例：</p>
<pre class="prettyprint"><code lang="python">import sys
for line in open(sys.argv[1], 'r'):
    print(line, end = '')
</code></pre>
<p>這個範例可以使用命令列引數，指定要讀取的檔案名稱，如果沒有提供命令列引數的話，就會由於 <code>argv[1]</code> 沒有元素，而發生存取超出索引範圍的錯誤：</p>
<pre class="prettyprint"><code lang="python">Traceback (most recent call last):
  File "test.py", line 2, in &lt;module&gt;
    for line in open(sys.argv[1], 'r'):
IndexError: list index out of range
</code></pre>
<p>在 Python 中程式若發生錯誤會引發例外，以上例而言就是引發 <code>IndexError</code>，如果程式沒有處理例外而丟出至執行環境，則會顯示例外追蹤（Traceback）並中斷程式。如果想要處理例外，則可以使用 <code>try...except</code> 語句。</p>
<p>對於沒有指定檔案，接下來的讀取檔案流程就無法進行，因此對這個例外最好的處理方式，就是指示使用者應當提供檔案名稱，例如：</p>
<pre class="prettyprint"><code lang="python">import sys
try:
    for line in open(sys.argv[1], 'r'):
        print(line, end = '')
except IndexError:
    print('請提供檔案名稱')
    print('範例：')
    print('    python3.5 read.py your_file')
</code></pre>
<p>如果使用者輸入錯誤，引發的 <code>IndexError</code> 物件會被 <code>except</code> 比對型態是否相同，如果相同則執行對應的區塊。以上例而言，如果使用者輸入錯誤，就會顯示較友善的提示訊息（而不是丟個使用者看不懂的追蹤訊息）。</p>
<p><code>try..except</code> 的 <code>except</code> 可以指定多個物件，也可以有多個 <code>except</code>，如果沒有指定 <code>except</code> 後的物件型態，則表示捕捉所有引發的物件。</p>
<p>舉例來說，底下的範例中，若使用者於（Linux 中）輸入時輸入 Ctrl + D，會引發 <code>EOFError</code>，若輸 入 Ctrl + C，則會引發<code>KeyboardInterrupt</code>：</p>
<pre class="prettyprint"><code lang="python">import traceback
try:
    input = int(input('輸入整數：'))
    print('{0} 為 {1}'.format(input, '奇數' if input % 2 else '偶數'))
except ValueError:
    print('請輸入阿拉伯數字')
except (EOFError, KeyboardInterrupt):
    print('使用者中斷程式')
except:
    print('不明的程式中斷')
    traceback.print_exc()
</code></pre>
<p>由於 <code>except</code> 會捕捉所有引發的物件，必須置於最後。<code>traceback.print_exc()</code> 則可以顯示例外的追蹤訊息。</p>
<h1><code>finally</code></h1>
<p>對於先前讀取檔案的範例，如果指定的檔案名稱不存在的話，<code>open</code> 函式會引發 <code>FileNotFoundError</code>，對於這個錯誤，顯示給使用者較清楚的錯誤訊息，應該會是比較好的處理：</p>
<pre class="prettyprint"><code lang="python">import sys
try:
    file = open(sys.argv[1], 'r')
    for line in file:
        print(line, end = '')
    file.close() 
except IndexError:
    print('請提供檔案名稱')
    print('範例：')
    print('    python3.5 read.py your_file')
except FileNotFoundError:
    print('找不到檔案 {0}'.format(sys.argv[1]))
</code></pre>
<p>在〈<a href="UnicodeBasicIOPy3.html">Python 3 Tutorial 第二堂（1）Unicode 支援、基本 I/O</a>〉中曾經說過，在 <code>open</code> 傳回的實例被回收後，檔案就會關閉，不過，你沒辦法預期回收的時機，因此，檔案關閉的時機也就無法預期，如果你想在讀檔後，馬上關閉檔案以節省資源，可以如上頭，明確地呼叫 <code>file.close()</code>。</p>
<p>然而，這個範例有點問題，如果讀取檔案的過程中發生了錯誤，那麼就不會執行到 <code>file.close()</code>，若你想確保檔案一定會被關閉，可以定義在 <code>finally</code> 之中。例如：</p>
<pre class="prettyprint"><code lang="python">import sys
try:
    file = open(sys.argv[1], 'r')
    try:
        for line in file:
            print(line, end = '')
    finally:
        if file:
            file.close()
except IndexError:
    print('請提供檔案名稱')
    print('範例：')
    print('    python3.5 read.py your_file')
except FileNotFoundError:
    print('找不到檔案 {0}'.format(sys.argv[1]))
</code></pre>
<p>如上頭看到的，<code>try...except...finally</code> 可以形成巢狀結構，讀檔是在順利開檔之後要進行的流程，因此，使用了另一層 <code>try...finally</code> 來進行，如何針對不同層次的流程，處理不同層次發生的錯誤，這需要你依實際需求來思考。</p>
<h1><code>raise</code></h1>
<p>當然，在 <code>try...except...finally</code> 形成巢狀時，可讀性並不好，這時一個可行的處理方式是，將內層的流程封裝為一個函式，例如：</p>
<pre class="prettyprint"><code lang="python">import sys, logging

def for_each_line(file, do_action):
    try:
        for line in file:
            do_action(line)
    except:
        logger = logging.getLogger(__name__)
        logger.exception('未處理的例外')
    finally:
        file.close()

try:
    file = open(sys.argv[1], 'r')
    for_each_line(file, lambda line: print(int(line) + 10, end = ''))
except IndexError:
    print('請提供檔案名稱')
    print('範例：')
    print('    python3.5 read.py your_file')
except FileNotFoundError:
    print('找不到檔案 {0}'.format(sys.argv[1]))
</code></pre>
<p>在這個例子中，<code>for_each_line</code> 使用 <code>except</code> 捕捉所有的例外，然後使用 Python 的 <code>logging</code> API，以<code>logger.exception()</code> 記錄了例外訊息，不過，由於 <code>except</code> 捕捉例外並進行了處理，這個例外也就沒有再向外傳播了。</p>
<p>在這邊日誌處理，僅僅只是為了留下記錄，便於日後除錯，你也許希望例外能向外傳播，例如，你也許是在 GUI 程式中呼叫了 <code>for_each_line</code>，若它發生未處理的例外，想要能捕捉例外並以視窗顯示錯誤訊息，你可以使用 <code>rasie</code> 來引發例外：</p>
<pre class="prettyprint"><code lang="python">import sys, logging

def for_each_line(file, do_action):
    try:
        for line in file:
            do_action(line)
    except:
        logger = logging.getLogger(__name__)
        logger.exception('未處理的例外')
        raise
    finally:
        file.close()

try:
    file = open(sys.argv[1], 'r')
    for_each_line(file, lambda line: print(int(line) + 10, end = ''))
except IndexError:
    print('請提供檔案名稱')
    print('範例：')
    print('    python3.5 read.py your_file')
except FileNotFoundError:
    print('找不到檔案 {0}'.format(sys.argv[1]))
except ValueError:
    print('檔案中每一行，必須是代表整數的字串')
</code></pre>
<p><code>raise</code> 之後若沒有接上任何指定的例外，就是將 <code>except</code> 捕捉到的例外重新引發，你可以使用 <code>raise</code> 自行引發例外。例如：</p>
<pre class="prettyprint"><code lang="python">try:
    raise EOFError
except EOFError:
    print('EOFError')
</code></pre>
<p>可以在 <code>except</code> 捕捉到例外後，將例外物件指定給變數。例如：</p>
<pre class="prettyprint"><code lang="python">try:
     raise IndexError('11')
except IndexError as e:
    print(type(e), str(e))
    raise e
</code></pre>
<p>在語法方面若想進一步瞭解，可以參考：</p>
<ul>
<li><a href="../../Python/TryStatement.html">try、raise 陳述句</a></li>
<li><a href="../../Python/TryRaise.html">再看 try、raise</a></li>
<li><a href="../../Python/UserDefinedException.html">自訂例外</a></li>
</ul>
<p>實際上，語法是語法，更重要的是思考如何處理例外，這篇文件中僅僅提供了其中一個思考過程，如果你想認真地面對錯誤，別忘了看看這篇文件一開頭提到的那幾篇文章。</p>

            
           <br><br><div class="ad336-280" style="text-align: center;"><script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script><!-- 2015 新版型廣告 336 x 280 --><ins class="adsbygoogle" style="display:inline-block;width:336px;height:280px" data-ad-client="ca-pub-9750319131714390" data-ad-slot="9976409681"></ins><script>(adsbygoogle = window.adsbygoogle || []).push({});</script></div><br><div class="recommend" style="text-align: center;"><hr><script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script><!-- 自動大小回應相符內容 --><ins class="adsbygoogle" style="display:block" data-ad-client="ca-pub-9750319131714390" data-ad-slot="4953478487" data-ad-format="autorelaxed"></ins><script>(adsbygoogle = window.adsbygoogle || []).push({});</script></div>
        </article></main></div></body>
<script src="../../js/ui.js"></script>
</html>
<div class="analytics"><script async src="https://www.googletagmanager.com/gtag/js?id=G-QVQQYFSC8J"></script><script>window.dataLayer = window.dataLayer || [];function gtag(){dataLayer.push(arguments);}gtag('js', new Date());gtag('config', 'G-QVQQYFSC8J');</script></div>
